config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
	
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def sign_in(user)
		cookies.permanent.signed[:user_id] = user.id
		@current_user = user
	end

	def sign_out
		cookies.delete(:user_id)
		@current_user = nil
	end

	private
	def signed_in?
		!current_user.nil?
	end
	helper_method :signed_in?

	def current_user
		@current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
	rescue ActiveRecord::RecordNotFound
	end
	helper_method :current_user

	def private_access
		redirect_to :login unless signed_in?		
	end

	def public_access
		redirect_to root_path if signed_in?
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	# lo que va hacer es que cada vez que se llame algunas de esas rutas 
	# el va primero va ejecutar un metodo llamado private_access
	# exceptuando index y show porque esos metodos si deben ser visibles 
	# asi no estes autenticado pero los demas como create update edit si solo 
	# son paginas privadas
    
	before_action :private_access, except: [:index, :show]
	def index
		@products = Product.all		
	end

	def new
		@product = Product.new		
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path, notice:"El producto fue guardado con éxito"
		else
			render :new

		end	
	end

	def show
		@product = Product.find(params[:id])
		
	end

	def edit
		@product = Product.find(params[:id])		
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to products_path, notice: "el producto ha sido modificado con exito"
		else
			render :edit
		end 		
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy

		redirect_to products_path, notice: "El producto fue eliminado con éxito"
		
	end

	private
		def product_params
			params.require(:product).permit(:name,:url,:description)
			
		end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :public_access, except: [:destroy]
  def new
  end

  def create
  	user = User.find_by(email: params[:email])  	
  	if user && user.authenticate(params[:password])
  		sign_in(user)
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
		
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else
			render :new
		end
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :name, :twitter_handle)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def form_title
		@product.new_record? ? "Publicar Product" : "Modificar Producto"		
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producthunt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="alert alert-info"><%= flash[:notice]%></div>
    <% end %>

    <% if signed_in? %>
      <div> Hola  <%= current_user.name %> <%= link_to 'Salir', logout_path, method: :delete %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1> <%=form_title%> </h1>
			<%= form_for @product do |f| %>
				<div class="form-group">
					<%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del producto"%>
				</div>
				<div class="form-group">
					<%= f.url_field :url, class:"form-control input-lg", placeholder: "Ingresa la url del producto"%>
				</div>
				<div class="form-group">
					<%= f.text_area :description, class:"form-control input-lg", placeholder: "Ingresa la descripción del producto"%>
				</div>
				<div class="">
					<%= f.submit form_title, class:"btn btn-primary btn-lg btn-block"%>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			
			<h1>Productos</h1>
			<% if signed_in? %>
				<div class="text-right">
					<%= link_to "Publicar producto", new_product_path, class:"btn btn-primary"%>
				</div>
			<% end %>
			

			<table class="table">
				<tr>
					<th>Id</th>
					<th>Name</th>
					<th>URL</th>
					<th>Descripción</th>
					<th></th>

					<% @products.each do |product| %>
					<tr>
						<td><%= product.id%></td>
						<td><%= link_to product.name, product %></td>
						<td><%= product.url%></td>
						<td><%= product.description%></td>
						<td> 
							<% if signed_in? %>
								<%= link_to 'editar', edit_product_path(product) %>
								<%= link_to 'eliminar', product, method: :delete, data: {confirm: "¿Estás seguro de eliminar este producto?"} %>
							<% end %>
							
						</td>
					</tr>
					<% end %>

					<td></td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/products/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1>Publicar Producto</h1>
			<%= form_for @product do |f| %>
				<div class="form-group">
					<%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del producto"%>
				</div>
				<div class="form-group">
					<%= f.url_field :url, class:"form-control input-lg", placeholder: "Ingresa la url del producto"%>
				</div>
				<div class="form-group">
					<%= f.text_area :description, class:"form-control input-lg", placeholder: "Ingresa la descripción del producto"%>
				</div>
				<div class="">
					<%= f.submit "Publicar producto", class:"btn btn-primary btn-lg btn-block"%>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1><%= @product.name %></h1>
			<p> <%= @product.description%> </p>
			<a href=" <%= @product.url %>" target="_blank">¡Obtenlo!</a>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Crear Cuenta</h1>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
        </div>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre" %>
        </div>

        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="basic-addon1">@</span>
          <%= f.text_field :twitter_handle, class: "form-control input-lg", placeholder: "Twitter" %>
        </div>

        <div class="actions">
          <%= f.submit class: "btn btn-primary btn-block btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>